import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import "./globals.css";
import { NavbarSession } from "@/components/navbar/navbar";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    // Need Session provider for client components to work with auth
    <SessionProvider session={session}>
      <html lang="en">
        <body className={cn("bg-slate-200 overflow-hidden", inter.className)}>
          <NavbarSession />
          {children}
          <Toaster />
        </body>
      </html>
    </SessionProvider>
  );
}
